# mysql 5 驱动不同 高版本能兼容低版本 com.mysql.jdbc.Driver
spring:
  datasource:
    username: root
    password: 123456
    url:  jdbc:mysql://localhost:3306/mybatis_plus?usrSSL=false$useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# mysql 8 驱动不同 高版本能兼容低版本 com.mysql.cj.jdbc.Driver ,需要添加时区配置 serverTimezone=GMT%2B8